# Change these first
owner: NDLANO # Your GitHub organization or username, where this repository lives
repo: oppetid # The name of this repository

sites:
  - name: NDLA.no
    url: https://ndla.no
    icon: https://ndla.no/static/ndla-favicon.png
    assignees: 
      - ghveem
      - gunnarvelle
  - name: api.NDLA.no
    url: https://api.ndla.no
    icon: https://ndla.no/static/ndla-favicon.png
    assignees:  
      - ghveem
      - gunnarvelle
  - name: stier.ndla.no
    url: https://stier.ndla.no
    icon: https://ndla.no/static/ndla-favicon.png
    assignees:  
      - ghveem
  - name: liste.ndla.no
    url: https://liste.ndla.no
    icon: https://ndla.no/static/ndla-favicon.png
    assignees:  
      - ghveem
  - name: Taksonomi
    url: https://api.ndla.no/taxonomy/api-docs
    icon: https://ndla.no/static/ndla-favicon.png
    assignees:
      - gunnarvelle
      - ghveem
  - name: h5p.ndla.no
    url: https://ca.h5p.ndla.no/h5p
    icon: https://h5p.org/sites/all/themes/professional_themec/favicon.ico
    assignees:  
      - ghveem
  - name: ed (NDLA)
    url: $SECRET_EDNDLANO
    icon: https://ndla.no/static/ndla-favicon.png
    assignees:  
      - ghveem
      - gunnarvelle
  - name: test (NDLA)
    url: $SECRET_TESTNDLANO
    icon: https://ndla.no/static/ndla-favicon.png
    assignees:  
      - ghveem
      - gunnarvelle
  - name: staging (NDLA)
    url: $SECRET_STAGINGNDLANO
    icon: https://ndla.no/static/ndla-favicon.png
    assignees:  
      - ghveem
      - gunnarvelle
  - name: NDLA Support
    url: https://ndla.zendesk.com/
    icon: https://ndla.no/static/ndla-favicon.png
    expectedStatusCodes:
      - 301
      - 403
    assignees:  
      - ghveem
  
 # - name: blogg.ndla.no
 #   url: https://blogg.ndla.no
 #   icon: https://ndla.no/static/ndla-favicon.png
 #   assignees:  
 #     - ghveem
 # - name: arena (NDLA)
 #   url: $SECRET_ARENANDLANO
 #   icon: https://ndla.no/static/ndla-favicon.png
 #   assignees:  
 #     - ghveem
 # - name: matomo (NDLA)
 #   #url: $SECRET_tallNDLANO
 #   url: https://tall.ndla.no
 #   icon: https://ndla.no/static/ndla-favicon.png
 #   assignees:  
 #     - ghveem
#  - name: Udir.no
#    url: https://udir.no
#    icon: https://www.udir.no/Frontend/build/public/assets/images/logos/udir-logo.png
#  - name: GREP
#    url: https://data.udir.no/kl06/v201906/status/status_publisert
#    icon: https://www.udir.no/Frontend/build/public/assets/images/logos/udir-logo.png
#  - name: SNL
#    url: https://snl.no
#    icon: https://snl.no/packs/assets/images/snl_logo_dark-2c14cffc8dbfed734292bbd8a0422210.svg
#  - name: NRK skole
#    url: https://www.nrk.no/skole/
#    icon: https://gfx.nrk.no/z8cQnACxJjgPyAb5diF8IA6tpuqBHKgqPRjFPbRhg7Ew.jpg
#    maxResponseTime: 5000
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ndla.no
  theme: light
  #light, dark, night, ocean
  #baseUrl: /oppetid
  logoUrl: https://ndla.no/static/metalogo.jpg
  name: NDLA.no - Oppetid
  introTitle: "**Oppetid** overvaker statusen til utvalde nettsider"
  introMessage: For ndla.no - Dei flesta sakene heng saman, er t.d. api eller taksonomi nede, så påvirkar det resten. Er noko nede her, så har teknikarane fått varsel og jobbar med saka. 

  navbar:
    - title: Status
      href: https://status.ndla.no
    - title: Support
      href: https://ndla.zendesk.com  
    - title: NDLA.no på facebook
      href: http://facebook.com/ndla.no
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

robotsText: "User-agent: * \n Disallow: /"
i18n:
  activeIncidents: Aktive hendingar
  allSystemsOperational: Alt vel
  incidentReport: "Rapport for hending #$NUMBER  →"
  activeIncidentSummary: Opna $DATE med $POSTS postar
  incidentTitle: Detaljar for hending $NUMBER
  incidentDetails: Detaljar for hending
  incidentFixed: Fiksa
  incidentOngoing: Pågåande
  incidentOpenedAt: Opna
  incidentClosedAt: Lukka
  incidentSubscribe: Abonner på oppdateringar
  incidentViewOnGitHub: Sjå på GitHub
  incidentCommentSummary: Posta $DATE av $AUTHOR
  incidentBack: ← Tilbake til alle hendingar
  pastIncidents: Eldre hendingar
  pastIncidentsResolved: Løyst i løpet av $MINUTES minuttar. Sjå $POSTS post(ar)
  liveStatus: Status
  overallUptime: "Oppetid: $UPTIME"
  overallUptimeTitle: Oppetid
  averageResponseTime: "Gjenomsnittleg responstid: $TIMEms"
  averageResponseTimeTitle: Gjenomsnittleg responstid
  sevelDayResponseTime: Responstid siste 7 dagar
  responseTimeMs: Responstid (ms)
  up: Oppe
  down: Nede
  degraded: Nedgradert
  ms: ms
  loading: Lastar
  navGitHub: GitHub
  footer: Denne sida er laga med [open kjeldekode]($REPO) frå [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: For mange kall
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: Korleis kan du fikse det?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: Ein feil oppstod.
  errorIntro: Klarte ikkje å laste inn siste statusar.
  errorText: Prøv igjen om eit par straksar.
  errorHome: Til startsida
  pastScheduledMaintenance: Tidlegare planlagt vedlikehald
  scheduledMaintenance: Planlagt vedlikehald
  scheduledMaintenanceSummaryStarted: Starta $DATE og varar $DURATION minuttar
  scheduledMaintenanceSummaryStarts: Startar $DATE og varar $DURATION minuttar
  startedAt: Starta 
  startsAt: Startar 
  duration: Varar
  durationMin: $DURATION minuttar
  incidentCompleted: Fullført
  incidentScheduled: Planlagd
