# Change these first
owner: ghveem # Your GitHub organization or username, where this repository lives
repo: oppetid # The name of this repository

sites:
  - name: NDLA
    url: https://ndla.no
    icon: https://ndla.no/static/ndla-favicon.png
  - name: NDLA API
    url: https://api.ndla.no
    icon: https://ndla.no/static/ndla-favicon.png
  - name: NDLA H5P
    url: https://ca.h5p.ndla.no/h5p
    icon: https://ndla.no/static/ndla-favicon.png
  - name: NDLA Support
    url: https://ndla.zendesk.com/
    icon: https://ndla.no/static/ndla-favicon.png
  - name: Udir.no
    url: https://udir.no
    icon: https://www.udir.no/Frontend/build/public/assets/images/logos/udir-logo.png
  - name: GREP
    url: https://data.udir.no/kl06/v201906/status/status_publisert
    icon: https://www.udir.no/Frontend/build/public/assets/images/logos/udir-logo.png
  - name: SNL
    url: https://snl.no
    icon: https://snl.no/packs/assets/images/snl_logo_dark-2c14cffc8dbfed734292bbd8a0422210.svg
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /oppetid
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Oppetid
  introTitle: "**Oppetid** overvaker statusen til utvalde nettsider."
  introMessage: Open kjeldekode | Strake vegen frå github
  navbar:
    - title: Status
      href: https://ghveem.github.io/oppetid/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
