# Change these first
owner: ghveem # Your GitHub organization or username, where this repository lives
repo: oppetid # The name of this repository

sites:
  - name: NDLA
    url: https://ndla.no
  - name: NDLA API
    url: https://api.ndla.no
  - name: NDLA H5P
    url: https://ca.h5p.ndla.no/h5p
  - name: NDLA Support
    url: https://ndla.zendesk.com
  - name: Udir.no
    url: https://udir.no
  - name: GREP
    url: https://data.udir.no/kl06/v201906/status/status_publisert
  - name: SNL
    url: https://snl.no
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
