blank_issues_enabled: true
contact_links:
  - name: Feature requests and ideas
    url: https://github.com/upptime/upptime/discussions/new?category=ideas
    about: Suggest an idea for this project
  - name: Questions
    url: https://github.com/upptime/upptime/discussions/new?category=q-a
    about: Please ask and answer questions here
  - name: Planned maintenance
    url: https://upptime.js.org/docs/scheduled-maintenance
    about: <!--
start: 2021-02-24T13:00:00.220Z
end: 2021-02-24T14:00:00.220Z
expectedDown: ndla, ndla api
-->
